volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: bura843/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    image: bura843/foodgram_frontend:v0.1
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
        - backend

  infra:
    image: bura843/foodgram_infra
    volumes:
      - static:/staticfiles/
      - media:/app/media
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend